### ISSUE TITLE
Replacing nwipe with shred

### ISSUE THREAD

**Issue by lawrencesystems** [pgporada/autoshred#1]
Replacing nwipe with shred command instead.  On the raspberry pi nwipe will randomly lock up when shredding multiple hard drives at the same time.

**Comment by pgporada** [comment]
Thanks for letting me know! I believe my plan of action is going to be specifying the wiping utility in the config file. If I do that, the flags for that utility would need to be defined as well. Regardless, the config file will have an example.

**Comment by pgporada** [comment]
Done!
