### ISSUE TITLE
Question - What do all the rows in the shredder monitoring window mean?

### ISSUE THREAD

**Issue by Inkertus** [pgporada/autoshred#5]
None of them appear to be labelled.  I'm a Linux newb with no code experience so most of this is new to me.  I can figure out a few of them like drive ID and data write rate, but the rest of them are a mystery to me, like ETA if that's even there.  There does appear to be two time-formatted sections, but those don't count or read like the time...except the first one which I believe was the start time.  I also couldn't find documentation about the info present in the monitor window.  Can you explain them for me?

**Comment by pgporada** [comment]
My apologies for taking forever and a day to get back to you.

![autoshred](https://user-images.githubusercontent.com/2382565/54081962-49399d00-42e4-11e9-8aff-b259edd96b8f.png)
The section I think you're talking about is https://github.com/pgporada/autoshred/blob/master/autoshred.sh#L218-L220

What's happening there is I run the command `ps` with flags `aux`. The resulting fields shown in the terminal will be based off of this commands output. https://explainshell.com/explain?cmd=ps+aux
```
$ ps -aux -q 2003
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user      2003  0.1  0.8 226912 10096 pts/1    S+   03:33   0:00 vim
```


I then pipe `|` the output from the `ps aux` through `grep` to specifically find the string `shred`. Only lines that match the grep will be output to the screen. https://explainshell.com/explain?cmd=ps+aux+%7C+grep+%22shred%22
```
$ ps -aux -q 2003 | grep vim
user      2003  0.0  0.8 226912 10096 pts/1    S+   03:33   0:00 vim
```

Finally I use an extended grep to negate outputting lines that match either `grep` or `delete`. It's a fairly common occurrence when using `grep` that you'll pipe that directly to `grep -v grep`. https://explainshell.com/explain?cmd=ps+aux+%7C+grep+%22shred%22+%7C+egrep+-v+%27%28grep%7Cdelete%29%27

I hope this helps!

**Comment by Inkertus** [comment]
That helps a lot yes.  This combined with a google search fills in most of the blanks.
So as I understand it...
User,   ProcessID,  %CPU_usage,  % RAM_usage,  VirtualMemSize,  ResidentMemSize, TeleType???, StateOfOperation (R+ Running foreground, D+ foreground sleep), START (start time/day), TIME (time since start? doesn't appear to be a ETA as the # is too large), command vim (text editor?).
Thanks for the explanations!
