### ISSUE TITLE
Does it continue to run if you logout?

### ISSUE THREAD

**Issue by twerthi** [pgporada/autoshred#6]
Greetings!  I SSH into a RPi machine and started the script manually (versus configuring to run on boot).  I logged out of the session and noted that the HDD activity light on my HDD dock was still blinking, may I assume that means it's still running?  If so, may I also assume the dock HDD activity light will stop blinking once it's complete?

**Comment by pgporada** [comment]
You can check if there is a shred process still running like this. It
sounds like that's the case.
```
ps aux | grep shred
```

**Comment by pgporada** [comment]
If you run the program in `screen`, it will continue to run after you log
out. At that point you can keep inserting drives to wipe.

**Comment by twerthi** [comment]
I apologize for my lack of *nix knowledge.  The output is 

```
avahi      413  0.0  0.0   6916  2648 ?        Rs   Aug22   0:47 avahi-daemon: running [shredder.local]
root       832  0.0  0.0   3160   580 ?        S    Aug22   0:00 bash -c shred --force --zero --iterations=3 /dev/sda 2>/dev/null; if [ 0 -eq 0 ]; then echo 1 > /sys/block/sda/device/delete; fi;
root       836 10.4  0.0   1932   424 ?        D    Aug22 143:32 shred --force --zero --iterations=3 /dev/sda
shawn     5812  0.0  0.0   2840   592 pts/1    S+   18:56   0:00 grep --color=auto shred
```

I see two processes that reference shred, 832 and 836, did I accidentally start two?

**Comment by pgporada** [comment]
You're good to go is what I'm trying to say.

**Comment by twerthi** [comment]
Excellent.  I very much appreciate your prompt responses, thank you.

**Comment by twerthi** [comment]
One last question, if I may.  Am I correct in that once it's complete, the HDD activity light should stop blinking?  I've it running on an RPi4 against a 4TB HDD on a USB 2.0 connection, it's been running for almost two days.

**Comment by pgporada** [comment]
Nope, that looks fine. 832 is a bash process running the shred program. 836
is the actual shred process forked from 832.
